version: "3.7"
services:
  superset:
    image: apache/superset:0b49327cfb69b6596221cf3b8f7b8338d5772f27
    container_name: superset_app
    #    command: ["/app/docker/docker-bootstrap.sh", "app"]
    restart: always
    #ports:
    #  - 8088:8088
    #    user: *superset-user
    #    depends_on: *superset-depends-on
    volumes:
      - ./conf:/app/superset_home
    network_mode: "host"
#    volumes: *superset-volumes
#    environment:
#      CYPRESS_CONFIG: "${CYPRESS_CONFIG}"
volumes:
  superset_home:
    external: false
  db_home:
    external: false